export const styles = {
  navbar: {
    position: "fixed",
    top: 0,
    width: "100%",
    backgroundColor: "#2B6CB0",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1rem 2rem",
    zIndex: 1000,
    boxShadow: "0px 2px 8px rgba(0,0,0,0.1)",
    color: "#fff",
  },
  logo: {
    fontWeight: "700",
    fontSize: "1.5rem",
    cursor: "default",
  },
  navLinks: {
    listStyle: "none",
    display: "flex",
    gap: "2rem",
    margin: 0,
    padding: 0,
  },
  navItem: {
    fontSize: "1rem",
    transition: "all 0.3s ease",
  },

  banner: {
    height: "100vh",
    background:
      "linear-gradient(135deg, #6BC1FF 0%, #2B6CB0 100%)",
    color: "#fff",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    padding: "0 20px",
  },
  button: {
    marginTop: "1.5rem",
    padding: "14px 30px",
    fontSize: "1.2rem",
    fontWeight: "600",
    color: "#2B6CB0",
    backgroundColor: "#fff",
    borderRadius: "30px",
    textDecoration: "none",
    border: "none",
    cursor: "pointer",
    boxShadow: "0 4px 15px rgba(255, 255, 255, 0.6)",
    transition: "background-color 0.3s ease",
  },

  slider: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4rem 1rem",
    gap: "1.5rem",
    backgroundColor: "#f0f4f8",
  },
  slideContent: {
    maxWidth: "400px",
    textAlign: "center",
  },
  slideImage: {
    width: "100%",
    borderRadius: "10px",
    marginBottom: "1rem",
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
  },
  slideButton: {
    fontSize: "2.4rem",
    background: "none",
    border: "none",
    color: "#2B6CB0",
    cursor: "pointer",
    userSelect: "none",
    padding: "0 10px",
  },

  gallery: {
    padding: "4rem 2rem",
    backgroundColor: "#fff",
    textAlign: "center",
  },
  grid: {
    marginTop: "2rem",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: "1rem",
  },
  galleryImage: {
    width: "100%",
    height: "150px",
    objectFit: "cover",
    borderRadius: "8px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
  },

  about: {
    padding: "4rem 2rem",
    backgroundColor: "#f0f4f8",
    maxWidth: "800px",
    margin: "0 auto",
    textAlign: "center",
  },

  contact: {
    padding: "4rem 2rem",
    maxWidth: "600px",
    margin: "0 auto 4rem",
    backgroundColor: "#fff",
    borderRadius: "8px",
    boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  input: {
    padding: "12px",
    fontSize: "1rem",
    borderRadius: "8px",
    border: "1px solid #ccc",
    outline: "none",
    fontFamily: "'Poppins', Arial, sans-serif",
  },
  textarea: {
    padding: "12px",
    fontSize: "1rem",
    borderRadius: "8px",
    border: "1px solid #ccc",
    resize: "vertical",
    fontFamily: "'Poppins', Arial, sans-serif",
  },

  footer: {
    backgroundColor: "#2B6CB0",
    color: "#fff",
    textAlign: "center",
    padding: "1rem 2rem",
    fontSize: "0.9rem",
  },
};